### ISSUE TITLE
Panic on unwrap: Unsupported parameter in compress.rs

### ISSUE THREAD

**Issue by quietvoid** [rust-av/rav1e-by-gop#207]
Hi, I'm getting a panic when running `rav1e-by-gop` on commit https://github.com/rust-av/rav1e-by-gop/commit/4138959e16f715a80bae5a2c4fc3b76f520de0fd

```
rav1e-by-gop input.y4m --threads 16 -q 16 -o out.ivf                                                                                            ✘ INT  4s
Could not open workers file; using local encoding only
Found progress file for this encode. [R]esume or [O]verwrite?: O
Starting encode
Encoding using input from `input.y4m`, speed 6, quantizer 16, keyint 12-240
Using y4m decoder: 1920x804p @ 24000/1001 fps, 4:2:0, 10-bit
Using 3 encoder threads
[Overall] [00:00:00] Input Frame 1, Output Frame 0
[Idle] Loading frames...
[Idle] 
[Idle] 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Unsupported parameter" }', rav1e-by-gop/src/compress.rs:16:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any', rav1e-by-gop/src/bin/analyze.rs:440:10
```  

Built with `RUSTFLAGS="-C target-cpu=native" cargo build --release` on Archlinux.
Backtrace: https://0x0.st/i7sr.log

Thanks.

**Comment by shssoichiro** [comment]
Interesting, it's working on one of my machines but not on a different one. I'll revert the commit.
